export default Object.freeze({
  ABOUT_US: "About Us",
  ADD_ADDRESS: "Add Address",
  ADD_PROMO_CODE: "Add Promo Code",
  CART: "Cart",
  CASH_ON_DELIVERY: "Cash On Delivery",
  CONTACT_US: "Contact Us",
  CATEGORIES: "Home",
  FAQs: "FAQs",
  HELP: "Help",
  LISTING_DETAILS: "Listing Details",
  LISTING_EDIT: "Listing Edit",
  LISTING: "Listing",
  LOGIN: "Login",
  MESSAGES: "Messages",
  MY_ORDERS: "My Orders",
  PAYMENT: "Payment",
  PAYMENT_METHOD: "Payment Method",
  PROMO_ALERTS: "Promo Alerts",
  REGISTER: "Register",
  SUB_CATEGORIES: "Sub Categories",
  SUB_SUB_CATEGORIES: "Sub Sub Categories",
  SUCCESSFUL_ORDER: "Successful Order",
  TASK_DETAILS: "Order Details",
  SEARCH: "Search",
});
